### ISSUE TITLE
Task List & Issues Summary

### ISSUE THREAD

**Issue by ntwb** [ntwb/stylelint-config-bootstrap#1]
Issues summary:
- [x] Included `stylelint-config-standard` rules #2
- [x] Override `stylelint-config-standard` rules #3
- [x] New rules extending `stylelint-config-standard` rules #4
- [x] Add stylelint `stylelint-scss` plugin and rules #5
- [x] Add stylelint `stylelint-property-unknown` plugin and rules #6
- [x] Add stylelint `property-value-blacklist` rule to enforce `border: 0;` over `border: none;` #7
- [x] Ignored scsslint rules #8
- [x] Add `declaration-block-properties-order` via `PropertySortOrder` #9 
- [x] Update and send pull request to @PhilippBaschke's awesome [convert-to-stylelint](https://github.com/PhilippBaschke/convert-to-stylelint) guide

**Comment by ntwb** [comment]
Pull request sent: https://github.com/PhilippBaschke/convert-to-stylelint/pull/1

**Comment by ntwb** [comment]
Marking this as closed, releasing as 0.1.0

Further iterations on the config can be done in new issues/pull requests
